"""
Puerta "Dentro" · Studio 3D.

Preview rápido (cápside + N enzimas al azar, sin Packmol), colocador de sustrato
alrededor de la cápside (ilustrativo, tipo sustratinaitor), cálculo de radio interno
(PyMOL) y el experimento real de empaquetamiento (Packmol, múltiples réplicas).
"""

from __future__ import annotations

import datetime
import math
import random
import string
from pathlib import Path
from typing import Any, Dict, List, Optional

from src.core import paths
from src.services.common import (
    _config,
    _max_radius,
    _pdb_centroid,
    structure_path,
)


# --------------------------------------------------------------------------- #
# Radio interno
# --------------------------------------------------------------------------- #
def calculate_radius(capsid_name: str, save: bool = True) -> float:
    """Calcula el radio interno de una cápside vía PyMOL (dominio)."""
    from src.core.capsid import Capsid  # import perezoso: PyMOL es pesado

    path = structure_path("capside", capsid_name)
    if not path.exists():
        raise FileNotFoundError(f"Cápside no encontrada: {capsid_name}")

    capsid = Capsid(str(path))
    return capsid.calculate_internal_radius(save_to_file=save)


# --------------------------------------------------------------------------- #
# Preview rápido (colocación aleatoria, sin Packmol)
# --------------------------------------------------------------------------- #
def _random_positions(n: int, radius: float, min_distance: float) -> List[List[float]]:
    """Posiciones aleatorias uniformes dentro de una esfera, con distancia mínima."""
    effective_radius = radius * 0.8  # margen para que las enzimas no toquen la pared
    positions: List[List[float]] = []
    max_attempts = 1000

    for i in range(n):
        placed = False
        for _ in range(max_attempts):
            x, y, z = (random.uniform(-1, 1) for _ in range(3))
            if x * x + y * y + z * z > 1:
                continue
            candidate = [x * effective_radius, y * effective_radius, z * effective_radius]
            if all(
                math.dist(candidate, p) >= min_distance for p in positions
            ):
                positions.append(candidate)
                placed = True
                break
        if not placed:
            # No cupo respetando distancia: colocar en la superficie efectiva.
            x, y, z = (random.uniform(-1, 1) for _ in range(3))
            norm = math.sqrt(x * x + y * y + z * z) or 1.0
            positions.append(
                [x / norm * effective_radius, y / norm * effective_radius, z / norm * effective_radius]
            )
    return positions


def preview(
    capsid_name: str,
    enzyme_name: str,
    n_enzymes: int = 10,
    radius: float = 50.0,
    save_file: bool = False,
) -> Dict[str, Any]:
    """
    Genera un PDB combinado (cápside + N enzimas colocadas al azar) al instante.

    Devuelve un dict con el contenido del PDB, el nombre de archivo y, si se pidió,
    la ruta guardada. Es una vista previa: no ejecuta Packmol.
    """
    capsid_path = structure_path("capside", capsid_name)
    enzyme_path = structure_path("enzima", enzyme_name)
    if not capsid_path.exists() or not enzyme_path.exists():
        raise FileNotFoundError("Cápside o enzima no encontrada")

    capsid_content = capsid_path.read_text()
    enzyme_content = enzyme_path.read_text()

    min_distance = _config.get("packing.exclusion_radius", 10.0)
    positions = _random_positions(n_enzymes, radius, min_distance)

    # La cápside no está centrada en el origen: desplazo las enzimas a su
    # centroide para que queden realmente DENTRO de la cápside.
    cx, cy, cz = _pdb_centroid(capsid_content)
    positions = [[p[0] + cx, p[1] + cy, p[2] + cz] for p in positions]

    # La enzima tampoco está centrada en su origen: resto su propio centroide
    # para que cada copia caiga EXACTAMENTE en su posición asignada (si no, el
    # cúmulo entero se desplaza — el bug que se veía con GCase).
    ex, ey, ez = _pdb_centroid(enzyme_content)

    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines: List[str] = [
        f"HEADER    NANOCAPSULE GENERATED PDB                       {timestamp}",
        f"TITLE     {capsid_name} WITH {n_enzymes} {enzyme_name} ENZYMES",
        "REMARK    Generated by Nanocapsule MVP (preview service)",
        f"REMARK    Capsid: {capsid_name}",
        f"REMARK    Enzyme: {enzyme_name}",
        f"REMARK    Number of enzymes: {n_enzymes}",
        f"REMARK    Internal radius used: {radius:.1f} A",
        "",
        capsid_content,
    ]

    chain_ids = list(string.ascii_uppercase) + [
        f"{a}{b}" for a in string.ascii_uppercase for b in string.ascii_uppercase
    ]
    atom_counter = 10000

    for i, pos in enumerate(positions):
        lines.append(f"\nMODEL     {i + 1}")
        chain_id = chain_ids[i % len(chain_ids)][0]
        for line in enzyme_content.split("\n"):
            if line.startswith(("ATOM", "HETATM")):
                x = float(line[30:38]) if len(line) > 38 else 0.0
                y = float(line[38:46]) if len(line) > 46 else 0.0
                z = float(line[46:54]) if len(line) > 54 else 0.0
                new_line = (
                    line[:6]
                    + f"{atom_counter:5d}"
                    + line[11:21]
                    + chain_id
                    + line[22:30]
                    + f"{x - ex + pos[0]:8.3f}{y - ey + pos[1]:8.3f}{z - ez + pos[2]:8.3f}"
                    + (line[54:] if len(line) > 54 else "")
                )
                lines.append(new_line)
                atom_counter += 1
            elif line.strip():
                lines.append(line)
        lines.append("ENDMDL")

    lines.append("END")
    content = "\n".join(lines)

    timestamp_short = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{capsid_name}_{n_enzymes}enzimas_{enzyme_name}_{timestamp_short}.pdb"

    saved_path: Optional[Path] = None
    if save_file:
        paths.ensure_output_dirs()
        saved_path = paths.GENERATED_DIR / filename
        saved_path.write_text(content)

    return {
        "content": content,
        "filename": filename,
        "saved_path": str(saved_path) if saved_path else None,
        "n_enzymes": n_enzymes,
        "radius": radius,
    }


# --------------------------------------------------------------------------- #
# Colocador de sustrato ALREDEDOR de la cápside (ILUSTRATIVO — como sustratinaitor)
# --------------------------------------------------------------------------- #
# Plantilla de un sustrato: cadena corta de ~12 beads (glucosilceramida ilustrativa).
_SUBSTRATE_TEMPLATE = [(i * 1.6, 1.2 * math.sin(i * 0.9), 0.8 * math.cos(i * 0.6)) for i in range(12)]
_ST_CX = sum(p[0] for p in _SUBSTRATE_TEMPLATE) / len(_SUBSTRATE_TEMPLATE)
_ST_CY = sum(p[1] for p in _SUBSTRATE_TEMPLATE) / len(_SUBSTRATE_TEMPLATE)
_ST_CZ = sum(p[2] for p in _SUBSTRATE_TEMPLATE) / len(_SUBSTRATE_TEMPLATE)
_SUBSTRATE_CENTERED = [(x - _ST_CX, y - _ST_CY, z - _ST_CZ) for x, y, z in _SUBSTRATE_TEMPLATE]


def _rot(p, ax, ay, az):
    """Rota un punto por ángulos de Euler (determinista, para variar orientación)."""
    x, y, z = p
    y, z = y * math.cos(ax) - z * math.sin(ax), y * math.sin(ax) + z * math.cos(ax)
    x, z = x * math.cos(ay) + z * math.sin(ay), -x * math.sin(ay) + z * math.cos(ay)
    x, y = x * math.cos(az) - y * math.sin(az), x * math.sin(az) + y * math.cos(az)
    return x, y, z


def _around_positions(n, center, r_inner, r_outer, box, min_distance=7.0):
    """Posiciones en la cavidad (r<r_inner) o en el exterior (r>r_outer), dentro de la caja."""
    cx, cy, cz = center
    positions: List[List[float]] = []
    attempts = 0
    while len(positions) < n and attempts < n * 300:
        attempts += 1
        x, y, z = (random.uniform(-box, box) for _ in range(3))
        r = math.sqrt(x * x + y * y + z * z)
        if r < r_inner * 0.85 or r > r_outer * 1.04:   # cavidad o fuera del cascarón
            cand = [cx + x, cy + y, cz + z]
            if all(math.dist(cand, p) >= min_distance for p in positions):
                positions.append(cand)
    return positions


# Plantilla de sustrato generada desde un SMILES (RDKit), cacheada por SMILES.
_smiles_cache: Dict[str, List] = {}


def _smiles_to_template(smiles: str) -> List:
    """SMILES → coordenadas 3D de los átomos pesados (elem, x, y, z), centradas."""
    smiles = (smiles or "").strip()
    if not smiles:
        return None
    if len(smiles) > 400:
        raise ValueError("SMILES demasiado largo")
    if smiles in _smiles_cache:
        return _smiles_cache[smiles]

    from rdkit import Chem            # import perezoso
    from rdkit.Chem import AllChem

    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        raise ValueError(f"SMILES inválido: {smiles}")
    mol = Chem.AddHs(mol)
    params = AllChem.ETKDGv3()
    params.randomSeed = 42
    params.useRandomCoords = True
    params.maxIterations = 2000
    if AllChem.EmbedMolecule(mol, params) != 0:
        if AllChem.EmbedMolecule(mol, useRandomCoords=True, randomSeed=7, maxIterations=2000) != 0:
            raise ValueError("No se pudo generar la geometría 3D del SMILES")
    try:
        AllChem.MMFFOptimizeMolecule(mol, maxIters=500)
    except Exception:
        pass

    conf = mol.GetConformer()
    atoms = []
    for i, a in enumerate(mol.GetAtoms()):
        if a.GetSymbol() == "H":
            continue
        p = conf.GetAtomPosition(i)
        atoms.append((a.GetSymbol(), p.x, p.y, p.z))
    if not atoms:
        raise ValueError("SMILES sin átomos pesados")

    cx = sum(a[1] for a in atoms) / len(atoms)
    cy = sum(a[2] for a in atoms) / len(atoms)
    cz = sum(a[3] for a in atoms) / len(atoms)
    atoms = [(e, x - cx, y - cy, z - cz) for e, x, y, z in atoms]
    _smiles_cache[smiles] = atoms
    return atoms


def preview_substrate(capsid_name: str, n: int = 60, smiles: str = None,
                      save_file: bool = False) -> Dict[str, Any]:
    """PDB combinado: cápside (modelo 0) + N copias de sustrato colocadas alrededor.

    Si `smiles` viene, el sustrato se genera desde ese SMILES con RDKit; si no, se
    usa la plantilla sintética simple.
    """
    capsid_path = structure_path("capside", capsid_name)
    if not capsid_path.exists():
        raise FileNotFoundError(f"Cápside no encontrada: {capsid_name}")

    # Plantilla del sustrato: (elemento, x, y, z) centrada en el origen.
    tpl = _smiles_to_template(smiles)
    if tpl is None:
        tpl = [("C", x, y, z) for x, y, z in _SUBSTRATE_CENTERED]

    capsid_content = capsid_path.read_text()
    center = _pdb_centroid(capsid_content)
    r_outer = _max_radius(capsid_content, center)
    r_inner = r_outer * 0.72          # cavidad interna aprox (ilustrativo)
    box = r_outer * 1.2               # caja del tamaño de la cápside (como sustratinaitor)

    positions = _around_positions(n, center, r_inner, r_outer, box)

    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines: List[str] = [
        f"HEADER    NANOCAPSULE SUBSTRATE PLACEMENT                {timestamp}",
        f"TITLE     {capsid_name} WITH {len(positions)} SUBSTRATE COPIES (AROUND)",
        f"REMARK    Sustrato: {'SMILES ' + smiles if smiles else 'plantilla simple'}",
        "",
        capsid_content,
    ]

    chain_ids = list(string.ascii_uppercase)
    atom = 20000
    for i, pos in enumerate(positions):
        lines.append(f"\nMODEL     {i + 1}")
        chain = chain_ids[i % len(chain_ids)]
        res = (i % 9999) + 1
        for j, (elem, ax, ay, az) in enumerate(tpl):
            bx, by, bz = _rot((ax, ay, az), i * 0.7, i * 1.3, i * 0.5)
            x, y, z = pos[0] + bx, pos[1] + by, pos[2] + bz
            name = (elem + str(j))[:4]
            lines.append(
                f"HETATM{atom:5d} {name:<4} LIG {chain}{res:4d}    "
                f"{x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00          {elem:>2}"
            )
            atom += 1
        lines.append("ENDMDL")
    lines.append("END")
    content = "\n".join(lines)

    saved_path: Optional[Path] = None
    if save_file:
        paths.ensure_output_dirs()
        ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        saved_path = paths.GENERATED_DIR / f"{capsid_name}_sustrato_{len(positions)}_{ts}.pdb"
        saved_path.write_text(content)

    return {"content": content, "n": len(positions), "saved_path": str(saved_path) if saved_path else None}


# --------------------------------------------------------------------------- #
# Experimento real (Packmol, múltiples réplicas en paralelo)
# --------------------------------------------------------------------------- #
def run_experiment(
    capsid_name: str,
    enzyme_name: str,
    n_replicas: Optional[int] = None,
) -> Dict[str, Any]:
    """
    Ejecuta el empaquetamiento máximo real con Packmol y múltiples réplicas.

    Bloquea hasta terminar (puede tardar minutos). En una versión escalable esto
    se movería a una cola de trabajos en background; aquí es síncrono a propósito
    para el prototipo.
    """
    from src.core.experiment_runner import ExperimentRunner

    if n_replicas is None:
        n_replicas = _config.get("experiments.n_replicas", 10)

    capsid_path = structure_path("capside", capsid_name)
    enzyme_path = structure_path("enzima", enzyme_name)
    if not capsid_path.exists() or not enzyme_path.exists():
        raise FileNotFoundError("Archivos de estructura no encontrados")

    paths.ensure_output_dirs()
    runner = ExperimentRunner(output_base_dir=str(paths.OUTPUT_DIR), config=_config)
    results = runner.run_maximum_packing(
        capsid_file=str(capsid_path),
        enzyme_file=str(enzyme_path),
        capsid_name=capsid_name,
        enzyme_name=enzyme_name,
        n_replicas=n_replicas,
    )
    return results
